- DataStructure/1.Array/Largest substring with no duplicate.cpp
> Create Largest substring with no duplicate.cpp

- DataStructure/1.Array/catalan_numbers.cpp
C++ program to find the nth Catalan Number
> Created catalan_numbers.cpp

- LeetCode/217. Contains Duplicate.cpp
> Added a LeetCode Folder

- LeetCode/53.Maximum_subarray.cpp
> 53.Maximum_subarray.cpp

- GeeksForGesks/Question-> Merge Merge Two Sorted Array Without Extra Space
- GeeksForGesks/Solution-> Merge Two Sorted Array Without Extra Space
- GeeksForGesks/Test Cases With Explanation
Added the Problem with beautiful Test Cases And Explanation to it.
Added one of the most efficient approach to solve the problem too.
> Added A question of merging TWO SORTED ARRAYS WITHOUT EXTRA SPACE

- Codeforces/C++/1579A.cpp
Added the solution for 1579A problem from codeforces.
>  Added 1579A

- Codeforces/C++/1569A.cpp
Added solution for the problem 1569A in codeforces.
> added 1569A

- DataStructure/Graph/bfs_rotten_oranges.cpp
C++ code to find minimum time required to make all oranges rotten using Breadth first Search Algorithm
> Created bfs_rotten_oranges.cpp

- LeetCode/Set_Mismatch.java
> set_mismatch solution added

- DataStructure/5.Queue/sliding_window_max_of_all_subarrays.cpp
This code will find the maximum elements in all sub-arrays of size 'k' in an array. Double-ended Queue data structure is used here using CPP STL.
> Created sliding_window_max_of_all_subarrays.cpp

- Algorithms/NumberTheory/SieveOfEratosthenes.cpp
Sieve of Eratosthenes is used to find the prime numbers till N in O(Nlog(logN)) time complexity, where N is a very large number.
> Added Sieve Of Eratosthenes

- LeetCode/13.Roman_to_Integer.java
- LeetCode/67.Add_Binary.java
Added leetcode problems :
13 ) Roman to Integer -->
**Example :**
Input: s = "III"
Output: 3
67 ) Add Binary -->
**Example:**
Input: a = "11", b = "1"
Output: "100"
> Added leetcode problems 13 and 67

- DataStructure/1.Array/three-pointers.c++
This problem of data structures is come from arrays concepts.
> three-pointers

- LeetCode/1011. Capacity To Ship Packages Within D Days.cpp
[Sliding Window Interview Problem by apimpulse] //hacktoberfest2021
> 1011. Capacity To Ship Packages Within D Days.cpp

- DataStructure/1.Array/kadane_algo.cpp
C++ program to print largest contiguous array sum using KADANE ALGORITHM
> New code kadane_algo.cpp

- LeetCode/C++/1008.cpp
- LeetCode/C++/1337. The K Weakest Rows in a Matrix.cpp
the two solution is been added in leetcode diretory
> added 2 code

- Algorithms/Mathematics/eratosthenes_sieve.cpp
Program to find the prime numbers in O(nloglogn)
> Created eratosthenes_sieve.cpp

- Codeforces/C++/1550B.cpp
I have Added the solution code for Maximum Cost Deletion (Problem B) which was a part of Educational Codeforces Round 111 (Rated for Div. 2).
> Added 1550B solution in CPP

- LeetCode/354. Russian Doll Envelopes.cpp
Added Leetcode Hard problem 354 Russian Doll Envelopes
> Added Leetcode Hard problem 354

- Algorithms/NumberTheory/SegementedSieve.cpp
Added Segemented-sieve-Algorithm with practice problem.U can merge it : )
> Added Segemented-sieve

- Algorithms/Greedy/Indian_coin_change.cpp
- Algorithms/Greedy/activity_selection.cpp
- Algorithms/Greedy/fractional_knapsack.cpp
- Algorithms/Greedy/max_min_diff.cpp
- Algorithms/Greedy/remove_duplicates_from_String.cpp
Added some problems which can be solved through Greedy Algorithm.
> Added some problems in Greedy.

- Algorithms/NumberTheory/chinese_remainder.cpp
> Chinese remainder theorem added.

- Algorithms/PatternSearching/KMP Algorithm for Pattern Searching.cpp
KMP Algorithm for Pattern Searching in C++
important for interviews
> Create KMP Algorithm for Pattern Searching.cpp

- Codechef/SeptemberLunchtime/ALBOFACE.cpp
- Codechef/SeptemberLunchtime/SOD3.cpp
- Codechef/SeptemberLunchtime/TWODISH.cpp
- Codechef/SeptemberLunchtime/UNQEQ.cpp
- Codechef/SeptemberLunchtime/VDATES.cpp
Issue resolved
Codechef September Lunchtime 2021 Solutions
> Sept Lunchtime Solutions Added

- LeetCode/1027. Longest Arithmetic Subsequence.cpp
- LeetCode/1751 Maximum Number of Events That Can Be Attended II.cpp
- LeetCode/2008.Maximum Earnings From Taxi.cpp
- LeetCode/322 Coin Change.cpp
- LeetCode/39 Combination Sum.cpp
- LeetCode/40 Combination Sum II.cpp
1. Combination Sum 2 [https://leetcode.com/problems/combination-sum-ii/](url)
2. Combination Sum [https://leetcode.com/problems/combination-sum/](url)
3. Longest Arithmetic Subsequence [https://leetcode.com/problems/longest-arithmetic-subsequence/](url)
4. Coin Change [https://leetcode.com/problems/coin-change/](url)
5. Maximum Earnings From Taxi [https://leetcode.com/problems/maximum-earnings-from-taxi/](url)
6. Maximum Number of Events That Can Be Attended II [https://leetcode.com/problems/maximum-number-of-events-that-can-be-attended-ii/](url)
Please do review my request and merge it. Thanks !
> Added 6 Leetcode problems.

- Codeforces/C++/1579B.cpp
- Codeforces/C++/1579C.cpp
- Codeforces/C++/1579D.cpp
- Codeforces/C++/1579E1.cpp
- Codeforces/C++/1579E2.cpp
I have added my solutions to 5 tasks (Task B,C,D,E1 and E2) of Codeforces Round 744 to the repo. Solution of Problem A was already present in the repo.
Please do review my request and merge it!
Thanks!
> Added Solutions to 5 tasks of Codeforces Round 744

- Algorithms/Recursions/Factorial.cpp
- Algorithms/Recursions/PrintTheNumberInSequence.cpp
- Algorithms/Recursions/fibonacci.cpp
- Algorithms/Recursions/sumTill_n.cpp
> Added recursions problems

- Algorithms/Searching/ternary-search.cpp
- Algorithms/Sorting/quicksort.cpp
Quick Sort Implementation in cpp
> Added Quick Sort Algorithm

- LeetCode/174. Dungeon Game.cpp
- LeetCode/32. Longest Valid Parentheses.cpp
- LeetCode/91. Decode Ways.cpp
- LeetCode/95. Unique Binary Search Trees II.cpp
- LeetCode/Lets Party !.cpp
> 5 problems added under leetcode section

- DataStructure/1.Array/Searching Array in Ascending order
This program will read total number of elements (N) and check value of N must be valid between 1-N, program will read N integer values (as array elements), print input elements with sorted array element (After sorting elements in Ascending Order).
> Searching array in ascending order.cpp
